// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dokieglbqvulgvuvzxix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRva2llZ2xicXZ1bGd2dXZ6eGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODY1MDgsImV4cCI6MjA2NTc2MjUwOH0.GbIlcvadVxjzrEqCq3y_OT0FafMLC7XrIE-RKyCuyOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);